<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MNGLauncher</AssemblyName>
    <RootNamespace>MNGLauncher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\mnglauncher.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="OriginLsx\OriginLsxServer.cs" />
    <None Include="OriginLsx\OriginLsxServer.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\mnglauncher.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
